### PR TITLE
Add ngspice installation commands

### PR DESCRIPTION
**Pull request by chetanyagoyal**
Includes the required Docker commands (in docker/conda/Dockerfile) to install the latest version of ngspice in the docker image

### CODE REVIEW

**Review by saicharan0112 — COMMENTED** [review]
I just noticed that ngspice in part of the conda packages list. but do you think we need the packages that you added below?

**Comment by chetanyagoyal** [comment]
> I just noticed that ngspice in part of the conda packages list. but do you think we need the packages that you added below?

The conda package seems to get the ngspice-38 build from sourceforge, whereas we use the [http://git.code.sf.net/p/ngspice/ngspice](url) build.

**Comment by saicharan0112** [comment]
> > I just noticed that ngspice in part of the conda packages list. but do you think we need the packages that you added below?
> 
> The conda package seems to get the ngspice-38 build from sourceforge, whereas we use the [http://git.code.sf.net/p/ngspice/ngspice](url) build. So i think we should keep the Docker command which I added

ahh,understood. then remove ngspice from the list cuz with two installations, the one that is present in miniconda3 path will be taken first since we are adding that in the very beginning of $PATH.

**Comment by chetanyagoyal** [comment]
@msaligane @saicharan0112 i think this can be merged now

**Review by saicharan0112 — APPROVED** [review]
LGTM!

**Pull request merged**
