### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by cczw123**
I didn't find a place to change the docker container size. However, some people suggest to run apt clean and combining different run projects. I suggest to give this a try. I was not able to try this method in my repo as I didn't have the access to sai's docker image.

### CODE REVIEW

**Review by saicharan0112 — COMMENTED** [review]
@cczw123 can you please explain your updates? I don't think this is solving the docker size issue. BTW I think that got resolved.

**Comment by cczw123** [comment]
> @cczw123 can you please explain your updates? I don't think this is solving the docker size issue. BTW I think that got resolved.

**Comment by cczw123** [comment]
> 

Hi Sai, it may be helpful to clean the package after we finished installing it. I have a apt clean after installing:https://itsfoss.com/clear-apt-cache/ . Also people suggest to use combine multiple runs so it doesn't require that much layers:https://stackoverflow.com/questions/39223249/multiple-run-vs-single-chained-run-in-dockerfile-which-is-better

**Comment by cczw123** [comment]
Hi Sai,
it may be helpful to clean the package after we finished installing it. I
have a apt clean after installing:https://itsfoss.com/clear-apt-cache/ .
Also people suggest to use combine multiple runs so it doesn't require that
much layers:
https://stackoverflow.com/questions/39223249/multiple-run-vs-single-chained-run-in-dockerfile-which-is-better
Sincerely,
Jacky

**Pull request closed without merging**
