### PR TITLE
Added missing modelfile.csv after the previous PR

### PR DESCRIPTION
**Pull request by saicharan0112**
This file somehow got missed in the last PR and the flow broke. For some reason, I had to manually add this file rather from command line since git doesn't recognise this file changes.

### CODE REVIEW

**Comment by msaligane** [comment]
Thanks @saicharan0112 !
@joamatab There were a few things that broke after the last PR (generators folders renamed and missing files). Maybe the model file formatting?

**Comment by joamatab** [comment]
Hi Mehdi,

Following standard python packaging all packages that you want to ship with the openfasoc module should be inside the openfasoc module

this includes the generators folder

**Comment by msaligane** [comment]
Thanks @joamatab - I think in your last commit the generators folder was renamed openfasoc. Is that what you meant here?
There is also a top directory called openfasoc. So I just renamed back to generators since the sensors were failing. Not sure if this is what you meant?

**Comment by joamatab** [comment]
you can keep the generator folder name,

but i would move it inside the python package

This is what I would do, 

https://github.com/idea-fasoc/OpenFASOC/pull/45

let me know what you think
Joaquin

**Pull request merged**
