### PR TITLE
Fix dependencies.sh

### PR DESCRIPTION
**Pull request by chetanyagoyal**
Fixed dependencies.sh after the recent merges (@alibillalhammoud 's merges mainly). Updated klayout to the most recent version too

### CODE REVIEW

**Review by saicharan0112 — COMMENTED** [review]
why do you want to modify conda_versions.txt?

**Comment by saicharan0112** [comment]
can you please include the updates in the same PR #246 ? All address the same issue.

**Comment by chetanyagoyal** [comment]
> why do you want to modify conda_versions.txt?

It seems like they were the main reason for the initial conda package conflict errors along with not including the right channels. Changing both things together was the only thing that fixed it

**Comment by chetanyagoyal** [comment]
> can you please include the updates in the same PR #246 ? All address the same issue. Please refer to our discussion we had on Slack

Committed all changes to #246, will close this PR if required

**Comment by saicharan0112** [comment]
> > can you please include the updates in the same PR #246 ? All address the same issue. Please refer to our discussion we had on Slack
> 
> Committed all changes to #246, will close this PR if required

Thanks

**Pull request closed without merging**
