### PR TITLE
LVS passing

### PR DESCRIPTION
**Pull request by alibillalhammoud**
1) modify cdl parser (adds top level subckt without redundant internal pins r_VIN or VIN)
2) modify lvspex.sh (process the extracted spice)
3) Insert process_extracted.py (adapts the extracted spice file by properly removing HEADER proxy pins, and internal pin r_VIN)
4) modify sky130_fd_sc_hd.spice (I only added attributes that were missing no proxy pins)

I wrote process_extracted.py in such a way that it is very specific in what it looks for. If it does not find the exact HEADER proxy pins it is looking for OR internal pin r_VIN in the top level subckt definition, it modifies nothing.

Flow needs to be working for this to run to completion...I verified that LVS was passing using Obed's fork. If you make the four changes listed above on Obed's fork, LVS should pass. 
Let me know if anything is incorrect, or I need to make any changes...

### CODE REVIEW

**Comment by saicharan0112** [comment]
Thanks! Let me check that with Obed's fork.

**Review by saicharan0112 — CHANGES_REQUESTED** [review]
I am marking this PR as "Request Changes", @alibillalhammoud . Let me know if it works after testing in the way we discussed once you update the scripts. Will be waiting for your updates.

**Comment by alibillalhammoud** [comment]
I pushed new commit which fixes a bug in removing proxy pins from HEADER instances. Remove the pins starting from the back, because if I remove a pin from the front that will change the index of the next pin to remove

**Comment by saicharan0112** [comment]
This PR is fixing the lvs issues with the latest version of dependencies (OpenROAD, Magic, Netgen, Yosys, skywater-pdk).

**Pull request merged**
