### PR TITLE
Update the tempsense flow to the current version of OpenROAD-flow-scripts

### LINKED ISSUE #73: Update the tempsense's flow scripts to the latest version of OpenROAD-flow-scripts
https://github.com/idea-fasoc/OpenFASOC/tree/main/openfasoc/generators/temp-sense-gen/flow
https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/tree/master/flow

### PR DESCRIPTION
**Pull request by luccareinehr**
This updates the tempsense flow to OpenROAD-flow-scripts commit id 1aa3fd3 (Aug 4 2022)
- I tested this update with a local installation of OpenROAD (v2.0-4526-gc525def45) and an installation in a conda environment (commit 5ca26d) from the [LiteX-hub channel](https://anaconda.org/LiteX-Hub), both successful. DRC with Magic (8.3.315) and LVS with Netgen (1.5.227) also don't produce errors in conda
- LVS with Netgen (`make netgen_lvs`) will now generate Magic .ext files in objects/.../netgen_lvs/ext and .spice files in objects/.../netgen_lvs/spice
- LEF modification for NDR is now made within the OpenROAD tool (no additional .py script) -- as mentioned in  https://openfasoc.readthedocs.io/en/latest/developers-guide.html

Some things to note:
- To see the final result in the OpenROAD GUI, go to the temp-sense-gen/flow/ directory and run `make gui_final`. You can also see intermediary steps with `make gui_floorplan`, `make gui_place` and `make gui_route`.
- The sky130hd platform dir, **common to all generators**, was also updated. Some files have changed significantly, such as `config.mk`, `fastroute.tcl`, `lef/sky130_fd_sc_hd_merged.lef`, which **WILL BREAK OTHER GENERATORS**. To keep support for generators with an older version of the flow scripts, a `backup/` folder inside the platform dir contains the older files. Such generators must be updated with this new directory path to work again (PLATFORM_DIR env variable in flow/Makefile, for example).
- The run_lvspex.sh script in `common/drc-lvs-check/` (**common to all generators**) was changed to relocate the generated .ext and .spice files in the objects dir. In the tempsense, I had to change `tools/temp-sense-gen.py` to get the correct path to the .spice file when copying it to the `work/` folder (which contains all the flow results). **THIS MAY BREAK OTHER GENERATORS**.
- The `merged_spacing.lef` file, previously used in the `cdl_parser.py` script, is not generated in the flow scripts anymore (by default). The cdl parser was thus updated not to use it (thanks @alibillalhammoud).
- This is still using `pdn.cfg` for OpenROAD's pdngen (related: #81)

For a more detailed view of what changed from the base OpenROAD-flow-scripts to OpenFASOC's tempsense generator flow, you can check the commit history in this fork: https://github.com/luccareinehr/OpenROAD-flow-scripts

Closes #73 #65

### CODE REVIEW

**Comment by luccareinehr** [comment]
@saicharan0112 I see one check fails with "permission denied" in a .py file, I got this in my conda installation too and just did chmod to fix it... should I do it here too?

**Comment by saicharan0112** [comment]
@luccareinehr Can try this? https://www.appsloveworld.com/swift/100/121/while-using-github-actions-im-facing-permission-denied-error

**Comment by luccareinehr** [comment]
for future reference: always run `pre-commit run --all-files` to pass the CI check

**Review by msaligane — COMMENTED** [review]
I see the `add_ndr_rule.py` file is deleted. How are you adding NDR?

**Comment by luccareinehr** [comment]
@msaligane NDR are added with `add_ndr_rules.tcl` under scripts/openfasoc/, using openroad (instead of opening the DEF in python and editing it)

**Comment by saicharan0112** [comment]
@luccareinehr Can you try to resolve these conflicts?

**Comment by luccareinehr** [comment]
@saicharan0112 Done!

**Comment by saicharan0112** [comment]
@msaligane you can now merge this PR. It also has the python code testing fixes

**Comment by msaligane** [comment]
Thanks @luccareinehr !

**Pull request merged**
