### PR TITLE
Add Inductor Structure gdsfactory Generator 

### PR DESCRIPTION
**Pull request by ryanrocket**
Revision 1 of inductor structure generator.

### CODE REVIEW

**Comment by mithro** [comment]
@joamatab - Could you help review this?

**Comment by msaligane** [comment]
@ryanrocket you need to do the pre-commit.

**Comment by joamatab** [comment]
This PR has only 1% of gdsfactory code, so im not sure im the right person to review this
99% of the code is using the klayout python API, which is fine. 
The main issue with the klayout API is that it lacks the concept of pins, which makes hard to connect and route things.
if you want to use this with skywater130 PDK you need to add some sort of pins and labels, so we can detect the ports

ideally we would rewrite the Pcells as gdsfactory [Pcells](https://gdsfactory.github.io/gdsfactory/notebooks/03_cells_autoname_and_cache.html)

Some areas for improvement (this applies for all OpenFASOC project)

- write tests
- write documentation
- Don't commit GDS outputs `output.gds` gds output should be tested in regression tests
- a lot of code seems to have been copied from mabrains repo, if that code was available in PyPi and klayout package manager, that would not be necessary. I would add the gdsfactory specific Pcells in the [skywater130 gdsfactory repo](https://github.com/gdsfactory/skywater130) as PRs. This repo has docs and tests, then in the OpenFASCOC i would import the `sky130` in `requirements.txt` and write only the generator, (not the PCell)

@mabrains

**Comment by ryanrocket** [comment]
Hey Joaquin, thanks for all of the feedback. I just met with Mehdi and we agree that a lot of the testing functionality and library management between klayout's API and gdsfactory need to be worked on. Unfortunately, right now we have a tapeout coming up in a few weeks and lack the time to work on these things. We are going to work on formalizing the way that pcells are handed between gdsfactory and klayout for SKY130 after the tapeout.

**Comment by joamatab** [comment]
Sounds good to me Ryan. Good luck with the tapeout

**Comment by msaligane** [comment]
> a lot of code seems to have been copied from mabrains repo, if that code was available in PyPi and klayout package manager, that would not be necessary. I would add the gdsfactory specific Pcells to the [skywater130 gdsfactory repo](https://github.com/gdsfactory/skywater130) as PRs. This repo has docs and tests, then in the OpenFASCOC i would import the sky130 in requirements.txt and write only the generator, (not the PCell)


Thanks @joamatab . Good point. I will hold on this PR till after the tapeout. Creating Pcells would take quite a bit of time. So we will address after the tapeout.

@ryanrocket I will keep this PR open till we discuss how to address this.

@saicharan0112 FYI - documentation feedback.

**Comment by saicharan0112** [comment]
@msaligane Noted! Thanks @joamatab

**Pull request closed without merging**
