### PR TITLE
Update save_images.tcl

### LINKED ISSUE #254: problem while running make sky130hd_temp
finish report_design_area
--------------------------------------------------------------------------
Design area 2551 u^2 19% utilization.

[ERROR GUI-0013] Unable to find visible display control at Pin Markers.
[ERROR GUI-0070] Error: save_images.tcl, 23 GUI-0013
Error: final_report.tcl, 63 GUI-0070
Command exited with non-zero status 1
Elapsed time: 0:00.67[h:]min:sec. CPU time: user 0.54 sys 0.11 (97%). Peak memory: 226936KB.
make[1]: *** [Makefile:568: /home/embedded/Documents/OpenFASOC/openfasoc/generators/temp-sense-gen/flow/logs/sky130hd/tempsense//6_report.log] Error 1
make[1]: Leaving directory '/home/embedded/Documents/OpenFASOC/openfasoc/generators/temp-sense-gen/flow'
[Error] Place and Route failed. Refer to the log file
make: *** [Makefile:48: sky130hd_temp] Error 1

question : 
1. Whats the use of Xyce and trilinos ?
2. How I can solve above problem ?

### PR DESCRIPTION
**Pull request by chetanyagoyal**
Fixes #254.
Updates the save_images.tcl file to accommodate for the changes made in Openroad-flow-scripts

### CODE REVIEW

**Comment by saicharan0112** [comment]
@chetanyagoyal this does fix the issue. Its like chicken and egg problem.. Let this update get merged so that the docker image (stable tag) will get updated with the latest openroad.

**Comment by saicharan0112** [comment]
@msaligane please merge this so that daily CI will take latest save_image.tcl file and run it with the latest openroad version.

**Comment by saicharan0112** [comment]
> > @chetanyagoyal this does fix the issue. Its like chicken and egg problem.. Let this update get merged so that the docker image (stable tag) will get updated with the latest openroad.
> 
> https://github.com/idea-fasoc/OpenFASOC/blob/25a97ea8eb57669582ddf5ab944edf067a713805/openfasoc/generators/temp-sense-gen/flow/scripts/final_report.tcl#L60-L63
> 
> These lines (which call the script) suggest that this script should not be run on the CI. Is it configured improperly perhaps?

Why do you think this should not be run on the CI?

**Comment by harshkhandeparkar** [comment]
> > > @chetanyagoyal this does fix the issue. Its like chicken and egg problem.. Let this update get merged so that the docker image (stable tag) will get updated with the latest openroad.
> > 
> > 
> > https://github.com/idea-fasoc/OpenFASOC/blob/25a97ea8eb57669582ddf5ab944edf067a713805/openfasoc/generators/temp-sense-gen/flow/scripts/final_report.tcl#L60-L63
> > 
> > These lines (which call the script) suggest that this script should not be run on the CI. Is it configured improperly perhaps?
> 
> Why do you think this should not be run on the CI?

`gui::show` probably means that it opens a GUI window. Also the comment above says that it should only run if OpenROAD is compiled with GUI.

**Comment by saicharan0112** [comment]
From the idea of the saving images and the GUI, it makes sense. But since
openroad is not throwing any error even though the command is executed
(remember that you cannot launch gui using this conda package) and the
check is able to catch the command changes, I think we should keep it as it
is.

**Review by saicharan0112 — APPROVED** [review]

**Comment by saicharan0112** [comment]
Thanks @chetanyagoyal . Tomorrow's check from the bot will help us test the latest openroad version with this update

**Pull request merged**
