### PR TITLE
LDO README

### PR DESCRIPTION
**Pull request by kalabYibeltal**

### CODE REVIEW

**Review by msaligane — CHANGES_REQUESTED** [review]
@kalabYibeltal markdown images should be inside the doc img folder and please keep all detail of each generator on its own page.

**Comment by saicharan0112** [comment]
@kalabYibeltal You might want to check the README file inside docs which is the link to the original ones.. Especially the path of images...

**Comment by kalabYibeltal** [comment]
> @kalabYibeltal markdown images should be inside the doc img folder and please keep all detail of each generator on its own page.

Okay.

**Comment by kalabYibeltal** [comment]
I have made the last changes in the "add final gds screenshot to temp-sensor readme" commit ( the second to last). the last commit is just merging with my fork branch.

**Comment by saicharan0112** [comment]
@kalabYibeltal I think your readme-addGenerators branch is not up-to-date.. Can you just check that, please?

**Comment by msaligane** [comment]
@kalabYibeltal Can you fix the conflicts and please ping me when you are available to meet.

**Pull request merged**
