### PR TITLE
Fix problem of make not exiting on subprocess errors

### PR DESCRIPTION
**Pull request by chetanyagoyal**

### CODE REVIEW

**Comment by saicharan0112** [comment]
thanks for the PR @chetanyagoyal ! I think your updates are already tested on the ldo generator and cryo-gen checks here. I can see that the generator exited after hitting an error in placement and quit running till the end.

**Review by saicharan0112 — CHANGES_REQUESTED** [review]
updates LGTM. Is fixing those "print" statements part also the plan for this PR?

**Comment by chetanyagoyal** [comment]
> updates LGTM. Is fixing those "print" statements part also the plan for this PR?

This seems like a slightly more involved issue, so I think i'll look into that in another PR

**Comment by saicharan0112** [comment]
> > updates LGTM. Is fixing those "print" statements part also the plan for this PR?
> 
> This seems like a slightly more involved issue, so I think i'll look into that in another PR

sounds good!. @msaligane this can be merged. To explain what this PR gives to the repo, this is mostly an enhancement for the generators flow. Earlier the generators run till the end eventhough they fail at some step. Now the generator exits after hitting an error in placement and quit running till the end. This will avoid that confusion for the users and also helps CI

**Comment by saicharan0112** [comment]
@chetanyagoyal , please update your PR so that we can merge this.

**Comment by chetanyagoyal** [comment]
> @chetanyagoyal , please update your PR so that we can merge this.

Are you talking about fixing the printing order in the generators?

**Comment by saicharan0112** [comment]
If you can do that in this same PR, that would be great. But I was talking
about synchronizing your PR with the main repo

**Review by saicharan0112 — APPROVED** [review]

**Pull request merged**
