### PR TITLE
DLDO: Add Xyce support, create seperate testbenches and documentation updates

### PR DESCRIPTION
**Pull request by lulu9312**
This PR includes:
1. Proper naming of spice template files and creation of seperate testbenches.
2. Added a new function raw_to_csv which converts raw data from simulations to csv files which can be used in regression.
3. Added Xyce simulation support and updated the tool install list in the main README.rst
4. Also updated the flow-ldo.rst and added README to ldo-gen. This fixes the issue #147

### CODE REVIEW

**Comment by saicharan0112** [comment]
@lulu9312 I don't think the specs are taking from the command line. After a quick view, it looks the specs are taking from the specs.json file. But @alibillalhammoud mentioned that specs can also be taking from the command line options while running make. I am referring to this line inside the main script. Can anyone of you both clarify this please?
https://github.com/idea-fasoc/OpenFASOC/blob/main/openfasoc/generators/ldo-gen/tools/ldo-gen.py#L90

**Comment by alibillalhammoud** [comment]
@saicharan0112 @lulu9312 specs can be taken command line or json spec file. To understand exactly how spec parse happens, look in configure workspace python file. Also I print out some useful notes about specifications to the console (scroll to the top).

**Comment by saicharan0112** [comment]
I see. But when I see the list of process running, I see that there is a ngspice simulation running with 1mA. However I see a difference in number of pt cells - (0.5mA - 7 and 1mA - 13). 
image

**Comment by alibillalhammoud** [comment]
@saicharan0112 looks like the naming of the sim script was changed so @lulu9312 would know

**Comment by lulu9312** [comment]
@saicharan0112 @alibillalhammoud  Yes I changed the naming of scripts. It should be updated based on the current. I will look into it.

**Comment by lulu9312** [comment]
@saicharan0112 I tried to give specs from command line. And it created correct sim files as per specs at my end.

**Review by msaligane — APPROVED** [review]

**Pull request merged**
