### PR TITLE
Update README.rst and add docker exit code inside workflows [CI]

### PR DESCRIPTION
**Pull request by saicharan0112**
remove info on the generators that is present already inside main documentation, tabular the generators data and point to the main documentation

### CODE REVIEW

**Comment by saicharan0112** [comment]
@msaligane please merge this first. It adds one more check to catch errors inside the docker container.

**Comment by saicharan0112** [comment]
FYI, ldo-gen is broker (regex issue #241 ) and there is something wrong with the cryo-gen as well. Temp-sense error is more of a python import that is coming from #226 .

**Comment by harshkhandeparkar** [comment]
> FYI, ldo-gen is broken (regex issue #241 ) and there is something wrong with the cryo-gen as well. Temp-sense error is more of a python import that is coming from #226 .

`ldo-gen` should be fixed in #229 but the Python error seems to be happening due to Python version `3.7.x`. When I made the PR, it was working for me locally but I use Python version 3.10+.

**Comment by saicharan0112** [comment]
> > FYI, ldo-gen is broken (regex issue #241 ) and there is something wrong with the cryo-gen as well. Temp-sense error is more of a python import that is coming from #226 .
> 
> `ldo-gen` should be fixed in #229 but the Python error seems to be happening due to Python version `3.7.x`. When I made the PR, it was working for me locally but I use Python version 3.10+.

I can confirm that this works for 3.10.

**Pull request merged**
