### PR TITLE
add code folders inside package

### PR DESCRIPTION
**Pull request by joamatab**
Hi Mehdi,

- This PR moves folders inside openfasoc package, following python packaging standards

@msaligane

### CODE REVIEW

**Comment by msaligane** [comment]
That looks good to me. Thanks @joamatab !
@saicharan0112 Could you please test this PR and see if anything breaks?

**Comment by saicharan0112** [comment]
Yes, I could do that!

**Comment by saicharan0112** [comment]
@joamatab I think you are missing the models/modelfile.csv file again. Can you please check that?

**Comment by joamatab** [comment]
Hi @saicharan0112 

where is that file on the main branch?

**Comment by msaligane** [comment]
@joamatab This is the modelfile: https://github.com/idea-fasoc/OpenFASOC/blob/main/generators/temp-sense-gen/models/modelfile.csv

**Comment by joamatab** [comment]
okay, there was a `.gitignore` ignoring csv files, so i removed the .gitignore and include the `modelfile.csv` file

let me know if that works well on your end 

Joaquin

**Comment by saicharan0112** [comment]
@joamatab You are missing sky130_fd_sc_hd__tt_025C_1v80.lib. It is at https://github.com/idea-fasoc/OpenFASOC/blob/main/common/platforms/sky130hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib

Can you please check this?

**Comment by saicharan0112** [comment]
[pr_logfile.txt](https://github.com/idea-fasoc/OpenFASOC/files/8579418/pr_logfile.txt)
Here is the logfile for the execution. Looks like there is some syntax error in ./util/def2gds.py file.

**Comment by saicharan0112** [comment]
image
Is this change required for python packaging? Cuz, without this "-> none", the flow is working fine.

**Comment by joamatab** [comment]
We can remove the type annotations `->None` as they are optional in python

I added the lib files
they were also being ignore in a .gitignore file
can you try again?

**Comment by saicharan0112** [comment]
@joamatab Yep! Its working. @msaligane , this PR is not breaking the flow anymore. You can merge it.

**Comment by joamatab** [comment]
Awesome!! we can add some more tests to ensure things don't break again :)

**Comment by saicharan0112** [comment]
Yeah.. I am actually building one.. I think the test should not only tell whether the flow broke or not but also need to find which files are missing/fault.

**Comment by msaligane** [comment]
Thank you guys!!

**Pull request merged**
