### PR TITLE
Add support for sky130_osu_15T_hs

### PR DESCRIPTION
**Pull request by Elon-J**

### CODE REVIEW

**Comment by msaligane** [comment]
@Elon-J @tuohangzeng Please check this PR - it has some conflicts

**Review by tuohangzeng — COMMENTED** [review]
Conflicts resolved

**Review by tuohangzeng — CHANGES_REQUESTED** [review]
Please add power ring generation to the design and save the final gds in the gds directory.

**Comment by Elon-J** [comment]
I have added it.

**Comment by Elon-J** [comment]
I have added it.

**Review by tuohangzeng — COMMENTED** [review]
They look good to me!

**Comment by msaligane** [comment]
Thanks @Elon-J @tuohangzeng it would be nice to add some doc on how to run these generators.

**Pull request merged**
