### PR TITLE
tempsense: add notebook with design space exploration (DSE) example to the docs

### PR DESCRIPTION
**Pull request by luccareinehr**
To do:
- [ ] Tidy up notebook explanation
- [ ] Change simulation to post-extraction (currently it's prePEX)
- [ ] Create link in Colab (and test it there)
- [ ] Change Docker image to the official CI one

### CODE REVIEW

**Comment by saicharan0112** [comment]
@luccareinehr Not sure if you know but OpenFASOC has a docker image where all the prerequisites tools are installed (https://hub.docker.com/repository/docker/msaligane/openfasoc). These are build everyday as part of CI. Tag with stable contains all the tools with the last set of versions that work with the latest OpenFASOC. Tag with latest contains the latest version of all tools that might or might not work with the latest OpenFASOC

**Comment by luccareinehr** [comment]
@saicharan0112 True, thanks, I'll try it out

Does the image also have the python libraries from `requirements.txt`?

**Comment by saicharan0112** [comment]
No. You might want to install them separately. Since that is dependent on
the repository itself, I didn't plan to include it inside the image though
I see no drawbacks to include it.

**Comment by luccareinehr** [comment]
@saicharan0112 Ohh I get it, I guess it makes sense because it's fewer dependencies to update. I'll try installing them separately since there's another library I had to include for interfacing with GCP anyway. Thanks!

**Comment by alibillalhammoud** [comment]
I want to note that post/prePEX simulation I have already done, you can specify when running the notebook using command line flags individually or both (i.e. you can run either prePEX or postPEX or both).

**Comment by msaligane** [comment]
@luccareinehr any progress on this?

**Comment by saicharan0112** [comment]
@luccareinehr not sure if are you planning to work on this or not.

**Comment by luccareinehr** [comment]
@saicharan0112 @msaligane I'll close the PR for now to clean the repo, then reopen it when I plan to finish working on the notebook

**Pull request closed without merging**
