### PR TITLE
Cryo Generator - Support for ODB

### PR DESCRIPTION
**Pull request by ryanrocket**
need to review bugs

### CODE REVIEW

**Comment by msaligane** [comment]
@ryanrocket Have you been able to add the changes we discussed?

**Comment by ryanrocket** [comment]
Finished resolving most `scripts` issues. New error stems from `/util/def2stream.py`. Refer bellow.
```
(/usr/bin/time -f "%Eelapsed %PCPU %MmemKB" stdbuf -o L /usr/bin/klayout -zz -rd design_name=cryoInst \
        -rd in_def=results/sky130hd/cryo/6_final.def \
        -rd in_files=" " \
        -rd config_file=../../../common/platforms/sky130hd/fill.json \
        -rd seal_file="" \
        -rd out_file=results/sky130hd/cryo/6_1_merged. \
        -rd tech_file=./objects/sky130hd/cryo/klayout.lyt \
        -rd layer_map= \
        -r ./util/def2stream.py) 2>&1 | tee ./logs/sky130hd/cryo/6_1_merge.log
ERROR: Reading /home/rw/work/open_pdks/sky130/sky130A/libs.tech/klayout/lvs/sky130.lylvs: XML parser error: error occurred while parsing element in line 31, column 49
ERROR: Reading /home/rw/work/open_pdks/sky130/sky130A/libs.tech/klayout/lvs/sky130.lylvs: XML parser error: error occurred while parsing element in line 31, column 49
## Skywaters 130nm PDK Pcells loaded.
['/home/rw/work/open_pdks/sky130/sky130A/libs.tech/klayout/pymacros', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/home/rw/.klayout/python']
[INFO] Reporting cells prior to loading DEF ...
[INFO] Reading DEF ...
[INFO] Clearing cells...
[INFO] Merging GDS/OAS files...
[INFO] Copying toplevel cell 'cryoInst'
INFO: Reading config file: ../../../common/platforms/sky130hd/fill.json
[INFO] Checking for missing cell from GDS/OAS...
[ERROR] LEF Cell 'sky130_fd_sc_hd__fill_8' has no matching GDS/OAS cell. Cell will be empty.
[ERROR] LEF Cell 'sky130_fd_sc_hd__fill_2' has no matching GDS/OAS cell. Cell will be empty.
[ERROR] LEF Cell 'sky130_fd_sc_hd__fill_1' has no matching GDS/OAS cell. Cell will be empty.
[ERROR] LEF Cell 'sky130_fd_sc_hd__fill_4' has no matching GDS/OAS cell. Cell will be empty.
[ERROR] LEF Cell 'sky130_fd_sc_hd__decap_4' has no matching GDS/OAS cell. Cell will be empty.
[ERROR] LEF Cell 'sky130_fd_sc_hd__tapvpwrvgnd_1' has no matching GDS/OAS cell. Cell will be empty.
[ERROR] LEF Cell 'sky130_fd_sc_hd__inv_1' has no matching GDS/OAS cell. Cell will be empty.
[ERROR] LEF Cell 'sky130_fd_sc_hd__dfxtp_1' has no matching GDS/OAS cell. Cell will be empty.
[ERROR] LEF Cell 'sky130_fd_sc_hd__nand2_1' has no matching GDS/OAS cell. Cell will be empty.
[INFO] Checking for orphan cell in the final layout...
[INFO] No orphan cells
[INFO] Writing out GDS/OAS 'results/sky130hd/cryo/6_1_merged.'
ERROR: Cannot determine format from filename in Layout.write
  ./util/def2stream.py:209
Command exited with non-zero status 1

```

**Comment by msaligane** [comment]
@ryanrocket thanks! can you fix the precommit.

**Comment by msaligane** [comment]
Can we add a regression test (spice sim) before merging this PR? It sounds like the main py script is broken and there are so many changes..

**Comment by saicharan0112** [comment]
@ryanrocket are you sure this generator is working?

**Review by saicharan0112 — CHANGES_REQUESTED** [review]
@ryanrocket I think its failing at the pdn generation stage. If you are OK, I will arrange the things around it and add a similar (and simple) check to see whether the generator is generating the gds without any errors in the end or not. While you figure out the flow block and fix it. 
Once you are done with the spice netlist generation from the template and magic, we can check the simulations. 

@msaligane are these things is what you have in mind too?

**Comment by saicharan0112** [comment]
@ryanrocket are you running the generator from `OpenFASOC/openfasoc/generators/cryo-gen/Makefile` or `OpenFASOC/openfasoc/generators/cryo-gen/flow/Makefile` ?

**Comment by ryanrocket** [comment]
@saicharan0112 I'm running it from `OpenFASOC/openfasoc/generators/cryo-gen/Makefile`. Running `make sky130hd_cryo_full` works all the way until LVS errors out at:
```
#----------------------------------------------------------------------
# LVS finished
#----------------------------------------------------------------------
mkdir: cannot create directory ‘tools/.././work’: File exists
genDir + args.outputDir: tools/.././work
flowDir: tools/../flow/
args.platform: sky130hs
designName: cryoInst
ls: cannot access 'tools/../flow//results/sky130hs/cryo': No such file or directory
Traceback (most recent call last):
  File "tools/cryo-gen.py", line 247, in <module>
    genDir + args.outputDir + "/" + args.platform + "/" + designName + ".gds",
  File "/home/rw/anaconda3/envs/test/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tools/../flow/results/sky130hs/cryo/6_final.gds'
make: *** [Makefile:36: sky130hs_cryo_full] Error 1
``` The other libs do not work though, and exit during synthesis with `make[1]: Nothing to be done for 'finish'`

**Comment by saicharan0112** [comment]
@ryanrocket : I clearly see that there is an issue with the pdn.tcl file. If possible, can you share the log file from your end too? Try this command `make sky130hd_cryo_full | tee -a cryo_gen_ryan_$(date +%m-%d-%Y).log` and check for the file with extension ".log" and share that with me here.

[cryo_gen_sai_02-01-2023.log](https://github.com/idea-fasoc/OpenFASOC/files/10552570/cryo_gen_sai_02-01-2023.log)
I am sharing the log file that is generated at my end, for your reference.

**Comment by msaligane** [comment]
@ryanrocket are you looking into this?

**Pull request merged**
