### PR TITLE
Added smoke testing for temperature sensor generator

### PR DESCRIPTION
**Pull request by saicharan0112**
* Added basic smoke test for temp_sense_generator to run on ubuntu
* Included test to check for generated files and errors during the process.
* Renamed "6_final_*.rpt" files in work folder to "module_name_*.rpt"
* During testing, PDK info is taken from saicharan0112/OpenFASOC:openfasoc_ci branch for now. Later, this PDK info can be taken from somewhere else (maybe idea-fasoc/OpenFASOC:openfasoc_ci branch ??)

### CODE REVIEW

**Comment by saicharan0112** [comment]
hei @joamatab, 
do you have any idea why pre-commit check is failing? It is not a syntax issue and the script in which the error is marked is working fine in other check (Test Temp-Sense Macro). 
https://github.com/idea-fasoc/OpenFASOC/runs/6248343277?check_suite_focus=true#step:4:71

**Comment by joamatab** [comment]
Hi,

it seems the formatter reccommends different while lines between functions

you need to install `pre-commit install` before `git commit`

if you have commited some code already that the formatter does not like you need to run `pre-commit run --all-files `

**Comment by saicharan0112** [comment]
@joamatab it worked! Thanks for the help. I am not aware of this. 
@msaligane looks like all checks are passed. Let me know if anything needs to be added/modified.

**Comment by msaligane** [comment]
Thanks!

**Comment by msaligane** [comment]
@saicharan0112 Can you clarify why you are using the PDK from: saicharan0112/OpenFASOC:openfasoc_ci 
Any particular reason?

**Comment by saicharan0112** [comment]
@msaligane No reason, we can have the PDK data in the idea-fasoc/OpenFASOC:openfasoc_ci (or some other name) branch to store the PDK too. I considered the last commit which passed CI in the open_pdks and skywater-pdk repos to build the PDK info. The stored the same in this branch. 
My concern is if we build the PDK everytime and if anything fails, we are not sure whether it is because of PDK or the openfasoc generator.

**Comment by msaligane** [comment]
@saicharan0112 Maybe we can add a check that verifies the PDK is built properly?

**Comment by saicharan0112** [comment]
> @saicharan0112 Maybe we can add a check that verifies the PDK is built properly?

Do we want that in this repo?

**Comment by saicharan0112** [comment]
@msaligane Please put this PR on hold. Let me add the PDK build too to the CI.

**Comment by saicharan0112** [comment]
@msaligane , I have another concern... If there is some issue with any cell or file in the PDK data which we don't know and when the generator fails, we will not be sure if it is because of the update to the generator or it is because of some file in the PDK data. 

Any thoughts on how to deal with this?

Before you start thinking, I have something but not sure if this is what you want...
* Build the PDK data and test it with the generator build from the HEAD~1 commit.. if it works, PDK data is good, else, PDK data is bad
* Now test the generator build from the HEAD commit... if it works, generator is good
* If it fails, generator is bad.

**Comment by saicharan0112** [comment]
Closing this PR for now. Will open another one with the updated CI setup.

**Pull request closed without merging**
