### PR TITLE
TempSense CDL Parser with correct pin order

### PR DESCRIPTION
**Pull request by alibillalhammoud**
TempSense CDL Parser with correct pin order

### CODE REVIEW

**Comment by saicharan0112** [comment]
@alibillalhammoud Looks like you are missing the pre-commit checks.. Its just a file cleaner for whitespaces, lines and other basic syntax issues - Check this comment and you should be able to pass this check (https://github.com/idea-fasoc/OpenFASOC/pull/46#issuecomment-1116121744)

**Review by saicharan0112 — CHANGES_REQUESTED** [review]
@alibillalhammoud  This is not working with the existing flow and the latest tools package. I need to look at the environment which you are working in.

**Review by saicharan0112 — APPROVED** [review]
Looks good to merge.

**Comment by msaligane** [comment]
Not sure what is happening with lint

**Comment by saicharan0112** [comment]
If I am correct, I think that it has entered a loop installing python dependencies using `make install` (especially sphinx). I observed this yesterday... Its not a serious issue though..

**Pull request merged**
